[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"
  environment = { NODE_VERSION = "14.9.0", NODE_ENV = "production" }

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[template.environment]
  ACKEE_MONGODB = "mongodb+srv://ufapro888:<password>@cluster0.43pvq.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  ACKEE_USERNAME = "UFAX"
  ACKEE_PASSWORD = "UFAX"
  ACKEE_ALLOW_ORIGIN = "*"
  ACKEE_TTL="3600000"